### ISSUE TITLE
[feature request] Support slackwave package

### ISSUE THREAD

**Issue by chaopeng** [SpaceinvaderOne/AutoSlackPack#8]
I found slackbuilds does not have git, maybe because [slackwave packages](https://packages.slackware.com/) has provide [git](https://mirrors.slackware.com/slackware/slackware-15.0/patches/source/git/). But the git version in unraid is low which could be an issue.

To support slackwave package easy for current impl, just add a env `SLACKDUILDFILE_URL`, if `SLACKDUILDFILE_URL` download it instead of `SLACKBUILD_DOWNLOAD`, user can keep use `SOURCE_DOWNLOAD` but point to `tar.xz` in https://mirrors.slackware.com/slackware/slackware-15.0/patches/source/git/. Then it should be good to go.

**Comment by bobbintb** [comment]
@chaopeng I'm not sure what you are asking. I think you mean Slackware, not Slackwave. This already has the Slackware package manager slackpkg. You are correct, slackbuilds doesn't have git because git is part of the official Slackware package repository and slackbuilds only has unofficial community slackbuild files. You can run `slackpkg update git` if it needs updating.

You say UnRAID has an older version of git but it's unclear what that has to do with AutoSlackPack. Are you trying to upgrade git on UnRAID? Did you mean AutoSlackPack has an older version of git?
